/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2024-04-15 09:07:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.Db.DBConnect;
import com.Dao.TextDao;
import com.User.*;
import com.User.UserDetails;
import java.net.http.HttpRequest;
import com.User.UserDetails;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/allComponents/homeNav.jsp", Long.valueOf(1712824812445L));
    _jspx_dependants.put("/allComponents/cdnFile.jsp", Long.valueOf(1703161738956L));
    _jspx_dependants.put("/allComponents/footer.jsp", Long.valueOf(1712742121254L));
    _jspx_dependants.put("/allComponents/SideNav.jsp", Long.valueOf(1713172060910L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.User");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.User.UserDetails");
    _jspx_imports_classes.add("com.Db.DBConnect");
    _jspx_imports_classes.add("com.Dao.TextDao");
    _jspx_imports_classes.add("java.net.http.HttpRequest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #f4f4f4;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .count-container {\n");
      out.write("	        max-width: 800px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            margin-left: 30%;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            padding: 50px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 150px;\r\n");
      out.write("            margin-bottom: 100px;\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	color: #333;\r\n");
      out.write("	font-size: 1.5em;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	padding-bottom: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#noteCount, #recycleBinCount {\r\n");
      out.write("	color: #555;\r\n");
      out.write("	font-size: 1.2em;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: transform 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#noteCount:hover, #recycleBinCount:hover {\r\n");
      out.write("	transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/348dc633e3.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/DashStyle.css\"> -->\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/style.css\"> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background: #E9C46A;\">\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/348dc633e3.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/DashStyle.css\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidenav\">\r\n");
      out.write("	<img id=\"logo\"\r\n");
      out.write("		style=\"gap: 10px; border-radius: 100px; margin-left: 60px;\" alt=\"\"\r\n");
      out.write("		src=\"https://th.bing.com/th/id/OIG4.H4.vGzSTck6UQ6qG8KtQ?w=100&h=100&rs=1&pid=ImgDetMain\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h4 class=\"text-white mx-5\">StudyScribe</h4>\r\n");
      out.write("\r\n");
      out.write("	<a href=\"Profile.jsp\">Profile</a> <a href=\"dashboard.jsp\">Dashboard</a>\r\n");
      out.write("	<button class=\"dropdown-btn\">\r\n");
      out.write("		Add Notes <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("	<div class=\"dropdown-container\">\r\n");
      out.write("		<a href=\"AddNotes.jsp\">Text Notes</a> \r\n");
      out.write("	</div>\r\n");
      out.write("	<button class=\"dropdown-btn\">\r\n");
      out.write("		View Notes <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("	<div class=\"dropdown-container\">\r\n");
      out.write("		<a href=\"ViewNotes.jsp\">Text Notes</a> \r\n");
      out.write("	</div>\r\n");
      out.write("	<button class=\"dropdown-btn\">\r\n");
      out.write("		Settings <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("	<div class=\"dropdown-container\">\r\n");
      out.write("		<a href=\"editProfile.jsp\">Edit Profile</a> <a href=\"ChangePwd.jsp\">Change\r\n");
      out.write("			Password</a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");

	UserDetails user = (UserDetails) session.getAttribute("currentUser");

	if (user != null) {
	
      out.write("\r\n");
      out.write("	<h5 class=\"text-white mx-3 text-bottom mt-5\">");
      out.print("Welcome "+ user.getName() );
      out.write("</h5>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("	/* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */\r\n");
      out.write("	let dropdown = document.getElementsByClassName(\"dropdown-btn\");\r\n");
      out.write("	let i;\r\n");
      out.write("\r\n");
      out.write("	for (i = 0; i < dropdown.length; i++) {\r\n");
      out.write("		dropdown[i].addEventListener(\"click\", function() {\r\n");
      out.write("			this.classList.toggle(\"active\");\r\n");
      out.write("			let dropdownContent = this.nextElementSibling;\r\n");
      out.write("			if (dropdownContent.style.display === \"block\") {\r\n");
      out.write("				dropdownContent.style.display = \"none\";\r\n");
      out.write("			} else {\r\n");
      out.write("				dropdownContent.style.display = \"block\";\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav\r\n");
      out.write("	class=\"navbar navbar-expand-lg border-bottom border-2 border-dark bg-custom navbar-custom\"\r\n");
      out.write("	style=\"width: 100%; position: fixed; top: 0%;\">\r\n");
      out.write("	<div class=\"container-fluid \">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav me-auto mb-2 mb-lg-0 mx-5\">\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<a href=\"#\" class=\"btn mx-3\" type=\"button\" data-bs-toggle=\"modal\"\r\n");
      out.write("				data-bs-target=\"#BackdropHome\"><i class=\"fa-solid fa-user-check\"></i>\r\n");
      out.write("				");

				UserDetails us = (UserDetails) session.getAttribute("currentUser");
				if (us != null) {
					out.println(us.getName());
				}
				
      out.write(" </a>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<a href=\"LogoutServlet\" class=\"btn mx-3\" type=\"submit\"><i\r\n");
      out.write("				class=\"fa-solid fa-user-plus\"></i>Logout</a>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("			</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	<div class=\"count-container\">\r\n");
      out.write("\r\n");
      out.write("		<h1>Notes Dashboard</h1>\r\n");
      out.write("\r\n");
      out.write("		");

				UserDetails user2 = (UserDetails) session.getAttribute("currentUser");
				if (user2 != null) {
					TextDao textDao = new TextDao(DBConnect.getConn());
					List<textNotes> list = textDao.getAllText(user2.getEmail());
					int totalNotesCount = list.size();
					int recycleBinCount = list.size()-list.size()+1;
					
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<a href=\"ViewNotes.jsp\">\r\n");
      out.write("			<p id=\"noteCount\">\r\n");
      out.write("				Total Count of Notes:\r\n");
      out.write("				");
      out.print(totalNotesCount);
      out.write("</p>\r\n");
      out.write("		</a> <a href=\"\">\r\n");
      out.write("			<p id=\"recycleBinCount\">\r\n");
      out.write("				Count of Deleted Notes:\r\n");
      out.write("				");
      out.print(recycleBinCount);
      out.write("</p>\r\n");
      out.write("		</a>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"modal fade\" id=\"BackdropHome\" data-bs-backdrop=\"static\"\r\n");
      out.write("		data-bs-keyboard=\"false\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h1 class=\"modal-title fs-5\" id=\"staticBackdropLabel\">Login\r\n");
      out.write("						Details</h1>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"text-center\">\r\n");
      out.write("						<i class=\"fa fa-user fa-3x\"></i>\r\n");
      out.write("						<h5></h5>\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>Full Name</th>\r\n");
      out.write("									<td>\r\n");
      out.write("										");

										if (user != null) {
										
      out.print(user.getName());
      out.write(' ');

 } else {
	 session.setAttribute("failed", "Login first or");
	 response.sendRedirect("login.jsp");
 }
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>Email ID</th>\r\n");
      out.write("									<td>\r\n");
      out.write("										");

										if (user != null) {
										
      out.print(user.getEmail());
      out.write(' ');

 }
 
      out.write("\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("\r\n");
      out.write("						</table>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("							data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"bg-dark\">\r\n");
      out.write("	<div class=\"container-fluid py-3 text-center text-white footer\">\r\n");
      out.write("		<p>\r\n");
      out.write("			Note: Please contact at <a\r\n");
      out.write("				href=\"mailto:vaishnavinagvanshi68675@gmail.com\">gmail.com</a>, if\r\n");
      out.write("			any errors occur. Designed <i class=\"fa-solid fa-wand-magic-sparkles\"></i>\r\n");
      out.write("			and developed by <span id=\"owner\">Vaishnavi Nagvanshi</span>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<p>All right reserved @CodeWithVaishnavi-2023-24</p>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
